apiVersion: v1
kind: Service
metadata:
  labels:
    app: phishy-mongodb-2
  name: mongo-nodeport-svc
  namespace: phishy
spec:
  ports:
  - port: 27018
    protocol: TCP
    targetPort: 27017
    nodePort: 32700
  selector:
    app: phishy-mongodb-2
  type: NodePort

