apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-nodeport-svc
  namespace: phishy
spec:
  ports:
  - port: 27018
    protocol: TCP
    targetPort: 27017
    nodePort: 33000
  selector:
    app: mongo
  type: NodePort

